### ISSUE TITLE
AttributeError: 'module' object has no attribute 'concatenate'

### ISSUE THREAD

**Issue by lim0606** [benanne/kaggle-ndsb#1]
I tried to run this codes with theano 0.7.0 and recent Lasagne 0.1 (today). 

`python train_convnet.py convroll4`

and I got following errors 

Traceback (most recent call last):
  File "train_convnet.py", line 70, in <module>
    train_loss = obj.get_loss()
  File "/usr/local/lib/python2.7/dist-packages/Lasagne-0.1dev-py2.7.egg/lasagne/objectives.py", line 71, in get_loss
    network_output = self.input_layer.get_output(input, *_kwargs)
 ........... 
  File "/usr/local/lib/python2.7/dist-packages/Lasagne-0.1dev-py2.7.egg/lasagne/layers/base.py", line 129, in get_output
    return self.get_output_for(layer_input, *_kwargs)
  File "/media/data/kaggle/ndsb/models/kaggle-ndsb/dihedral.py", line 107, in get_output_for
    return nn.utils.concatenate([
AttributeError: 'module' object has no attribute 'concatenate'

I saw this post https://github.com/benanne/Lasagne/issues/151.

Thus, I changed nn.utils.concatenate to T.concatenate. I think it seems to work fine. :)

**Comment by benanne** [comment]
As indicated in the docs, I recommend installing a specific commit of Lasagne if you want to use this code without problems (more specifically it's the version that was on most of our machines during the competition). Lasagne is still under heavy development so things are changing at a fast pace, and it is unlikely that the code in this repository will work with Lasagne 0.1 unmodified once it is released.

For now I guess this change is the only one needed, but there will be other (breaking) changes to Lasagne before it is released, and I don't plan to update this codebase for that. So your mileage may vary :)
